CREATE TABLE `tags` (
	`id` INT (10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR (255) NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `name` (`name`)
) ENGINE = INNODB DEFAULT CHARSET = utf8;

CREATE TABLE `tags_lang` (
	`id` INT (10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`object_id` INT (10) UNSIGNED NOT NULL,
	`lang_id` INT (10) UNSIGNED NOT NULL,
	`name` VARCHAR (255) NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `object_id` (`object_id`, `lang_id`) USING BTREE,
	CONSTRAINT `tags_lang_ibfk_1` FOREIGN KEY (`object_id`) REFERENCES `tags` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8;